name: Linting

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install yamllint==1.33.0

      - name: Lint YAML files
        run: yamllint .
        # Automatically uses ./.yamllint.yaml for configuration

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          # Automatically uses ./.golangci.yml for configuration
